export const siteConfig = {
  name: "Yago Menezes",
  title: "Web & Back-End Developer",
  description: "Portfolio website de Yago Menezes",
  accentColor: "#092f97",
  social: {
    email: "yago.ten.menezes@outlook.com",
    linkedin: "https://linkedin.com/in/ten-menezes",
    github: "https://github.com/tenmenezes",
    curriculo: "/others/Curriculo-YagoMenezes.pdf",
  },
  aboutMe:
    "Sou estudante de Análise e Desenvolvimento de Sistemas, apaixonado por tecnologia e programação. Gosto de criar sistemas web modernos, sistemas back-end e explorar novas ferramentas que me ajudam a evoluir como desenvolvedor.",
  skills: [
    "HTML",
    "CSS",
    "Bootstrap",
    "React.js",
    "Next.js",
    "Astro",
    "Ionic Framework",
    "Tailwind",
    "Chart.js",
    "Javascript",
    "PHP",
    "C#",
    "Java",
    ".NET Framework",
    "MySql",
    "PostgreSQL",
    "Linux",
    "Git",
    "Github",
    "Lógica de Programação",
    "Orientação a Objetos",
  ],
  projects: [
    {
      name: "Nexus SixTech WebSite",
      description:
        "Sistema web completo ainda em desenvolvimento, com dashboard administrativo, e um sistema completo de administrador, conectividade com banco físico, será passado para banco em nuvem futuramente.",
      link: "https://github.com/tenmenezes/Nexus_SixTech",
      skills: [
        "HTML",
        "CSS",
        "Tailwind",
        "Javascript",
        "Chart.js",
        "PHP",
        "MySql",
        "Git",
      ],
    },
    {
      name: "4Players WebSite",
      description:
        "WebSite desenvolvido como projeto de primeiro período da universidade, responsividade completa, acessibilidade e LocalStorage.",
      link: "https://tenmenezes.github.io/4Players",
      skills: [
        "HTML",
        "CSS",
        "Bootstrap",
        "Javascript",
        "Lógica de Programação",
        "Git",
      ],
    },
    {
      name: "Jogo de Xadrez em Console",
      description:
        "Jogo de Xadrez desenvolvido em C# com .NET Framework, feito para demonstrar habilidades práticas em programação orientada a objetos e lógica.",
      link: "https://github.com/tenmenezes/Project-Xadrez-Console",
      skills: [
        "C#",
        ".NET Framework",
        "Lógica de Programação",
        "Orientação a Objetos",
        "Git",
      ],
    },
  ],
  experience: [
    {
      company: "Projetos Pessoais e Acadêmicos",
      title: "Web & Back-End Developer",
      dateRange: "2022 - Presente",
      bullets: [
        "Atualmente desenvolvendo o projeto NextBlog, um blog moderno com Next.js 15+, autenticação e CMS integrado como parte do curso 'Next.js do Zero ao Avançado' (Udemy - Matheus Battisti).",
        "Desenvolvendo também o EcommerceNext, um e-commerce completo com Next.js, Tailwind e API Node.js, com foco em boas práticas e escalabilidade.",
        "Desenvolvendo também o sistema Nexus SixTech, um site de vendas de jogos com dashboard administrativo, tabelas dinâmicas, gráficos de desempenho e controle de estoque, utilizando PHP, MySQL, Chart.js e Tabulator.js.",
        "Implementei o 4Players, um site interativo para gamers, com foco em experiência de usuário e estilização avançada em HTML, CSS e JavaScript.",
        "Desenvolvi meu portfólio profissional com duas versões: uma principal no branch `main` e uma versão moderna com Astro e Tailwind, atualmente hospedada e publicada online no branch `Deploy`.",
        "Desenvolvi experimentos no projeto Astro-Projects, explorando o framework Astro e integrações com Tailwind, Motion e componentes reativos.",
        "Implementei o jogo Xadrez Console em C#, aplicando conceitos de Programação Orientada a Objetos (POO) e lógica de movimentação em console.",
      ],
    },
    {
      company: "Escola Técnica do Rio de Janeiro (ETERJ)",
      title: "Estagiário de T.I - Suporte Técnico",
      dateRange: "Out 2024 - Mar - 2025",
      bullets: [
        "Auxiliei e orientei mais de 50 alunos por semana em atividades práticas e teóricas, garantindo a continuidade das aulas em laboratório.",
        "Executei manutenções preventivas e corretivas em aproximadamente 200 equipamentos no ano, reduzindo interrupções nas atividades de sala de aula.",
        "Otimizei a conectividade para mais de 100 usuários diários, mantendo 99% de estabilidade da rede na sala dedicada.",
      ],
    },
  ],
  education: [
    {
      school: "Centro Universitário Augusto Motta (UNISUAM)",
      degree: "Tecnólogo - Análise e Desenvolvimento de Sistemas",
      dateRange: "2025 - 2027",
      achievements: [
        "Projetos acadêmicos focados em desenvolvimento web e mobile",
        "Participação ativa em projetos de desenvolvimento de software",
        "Cursos de extensão em metodologias ágeis e desenvolvimento web",
      ],
    },
    {
      school: "Escola Técnica do Rio de Janeiro (ETERJ)",
      degree: "Ensino médio Técnico em Informática",
      dateRange: "2022 - 2024",
      achievements: [
        "Aprendizado prático em linguagens como C#, C++, HTML, CSS, JavaScript, PHP, PostgreSQl, entre outros.",
        "Participação em feiras de tecnologia e inovação",
        "Desenvolvimento de projetos práticos em programação e automação com Arduíno.",
      ],
    },
  ],
};

export const skillIconsMap: Record<string, string> = {
  "HTML": "html",
  "CSS": "css",
  "Bootstrap": "bootstrap",
  "Astro": "astro",
  "React.js": "react",
  "Next.js": "next",
  "Ionic Framework": "ionic",
  "Tailwind": "tailwind",
  "Chart.js": "chartjs",
  "Javascript": "javascript",
  "PHP": "php",
  "C#": "csharp",
  "Java": "java",
  ".NET Framework": "dotnet",
  "MySql": "mysql",
  "PostgreSQL": "postgresql",
  "Linux": "linux",
  "Git": "git",
  "Github": "github",
  "Lógica de Programação": "logica",
  "Orientação a Objetos": "poo",
};
