export const siteConfig = {
  name: "Yago Menezes",
  title: "Software & Web Developer",
  description: "Portfolio website de Yago Menezes",
  accentColor: "#092f97",
  social: {
    email: "yago.ten.menezes@outlook.com",
    linkedin: "https://linkedin.com/in/ten-menezes",
    github: "https://github.com/tenmenezes",
    whatsapp: "https://wa.me/5521999922459?text=Ol%C3%A1%21%20Vim%20pelo%20seu%20portf%C3%B3lio%20e%20gostaria%20de%20conversar.",
    curriculo: "/others/curriculo_Full.pdf",
  },
  aboutMe:
    "Sou estudante de Análise e Desenvolvimento de Sistemas, formado como técnico de informática pela ETERJ - Escola Técnica do Rio de janeiro. Apaixonado por tecnologia e programação. Gosto de criar sistemas modernos, e explorar novas ferramentas que me ajudam a evoluir como desenvolvedor.",
  skills: [
    "HTML",
    "CSS",
    "Bootstrap",
    "Next.js",
    "Shadcn/ui",
    "Vercel",
    "Tailwind",
    "Chart.js",
    "Javascript",
    "Typescript",
    "PHP",
    "C#",
    ".NET Framework",
    "MySql",
    "Linux",
    "Git",
    "GitHub",
    "Trello",
  ],
  projects: [
    {
      name: "AgenteIA — Gerador Inteligente de RoadMap",
      description:
        "Aplicação full-stack em Next.js que gera um roadmap personalizado para cada usuário via IA, exibido em Markdown e disponível para download em PDF. Interface responsiva, validação com Zod e API serverless integrada para processamento das respostas.",
      link: "https://agent-ia-beta.vercel.app/",
      skills: [
        "Next.js",
        "Tailwind",
        "Typescript",
        "Node.js",
        "Postman",
        "Shadcn/ui",
        "Vercel",
        "Git",
      ],
    },

    {
      name: "SystemCheck Landing Page",
      description:
        "Desenvolvi uma landing page interativa e responsiva voltada para uma empresa de tecnologia e diagnóstico digital. A interface foca em clareza visual, microinterações elegantes e performance otimizada, destacando seções de serviços, diferenciais e depoimentos. A página foi projetada com arquitetura modular e escalável, servindo como base para futura integração de um sistema de suporte técnico e simulação de atendimentos.",
      link: "https://systemcheck.vercel.app/",
      skills: [
        "Next.js",
        "React.js",
        "Typescript",
        "Tailwind",
        "Vercel",
        "Git",
        "GitHub",
      ],
    },

    {
      name: "Brandify Landing Page",
      description:
        "Desenvolvi uma landing page moderna e responsiva. O site foca em performance, design intuitivo e conversão, oferecendo recursos como layouts responsivos, SEO integrado, personalização fácil e suporte dedicado. Inclui seções de hero, funcionalidades, depoimentos de clientes, preços e FAQ, com animações suaves implementadas via Framer Motion.",
      link: "https://tenmenezes.github.io/Brandify",
      skills: ["React.js", "Vite", "Framer Motion", "Tailwind", "Git"],
    },
    {
      name: "Nexus SixTech WebSite",
      description:
        "Sistema web completo ainda em desenvolvimento, com dashboard administrativo, e um sistema completo de administrador, conectividade com banco físico, será passado para banco em nuvem futuramente.",
      link: "https://github.com/tenmenezes/Nexus_SixTech",
      skills: [
        "HTML",
        "CSS",
        "Tailwind",
        "Javascript",
        "Chart.js",
        "PHP",
        "MySql",
        "Git",
        "Metodologias Ágeis",
      ],
    },
    {
      name: "4Players WebSite",
      description:
        "WebSite desenvolvido como projeto de primeiro período da universidade, responsividade completa, acessibilidade e LocalStorage.",
      link: "https://tenmenezes.github.io/4Players",
      skills: [
        "HTML",
        "CSS",
        "Bootstrap",
        "Javascript",
        "Metodologias Ágeis",
        "Lógica de Programação",
        "Git",
      ],
    },
    {
      name: "Jogo de Xadrez em Console",
      description:
        "Jogo de Xadrez desenvolvido em C# com .NET Framework, feito para demonstrar habilidades práticas em programação orientada a objetos e lógica.",
      link: "https://github.com/tenmenezes/Project-Xadrez-Console",
      skills: [
        "C#",
        ".NET Framework",
        "Lógica de Programação",
        "Orientação a Objetos",
        "Git",
      ],
    },
  ],
  experience: [
    {
      company: "Escola Técnica do Rio de Janeiro (ETERJ)",
      title: "Estagiário de T.I - Suporte Técnico",
      dateRange: "Out 2024 - Mar - 2025",
      bullets: [
        "Auxiliei e orientei mais de 50 alunos por semana em atividades práticas e teóricas, garantindo a continuidade das aulas em laboratório.",
        "Executei manutenções preventivas e corretivas em aproximadamente 200 equipamentos no ano, reduzindo interrupções nas atividades de sala de aula.",
        "Otimizei a conectividade para mais de 100 usuários diários, mantendo 99% de estabilidade da rede na sala dedicada.",
      ],
    },
  ],
  education: [
    {
      school: "Centro Universitário Augusto Motta (UNISUAM)",
      degree: "Tecnólogo - Análise e Desenvolvimento de Sistemas",
      dateRange: "2025 - 2027",
      achievements: [
        "Projetos acadêmicos focados em desenvolvimento web e mobile",
        "Participação ativa em projetos de desenvolvimento de software",
        "Cursos de extensão em metodologias ágeis e desenvolvimento web",
      ],
    },
    {
      school: "Escola Técnica do Rio de Janeiro (ETERJ)",
      degree: "Ensino médio Técnico em Informática",
      dateRange: "2022 - 2024",
      achievements: [
        "Aprendizado prático em linguagens como C#, C++, HTML, CSS, JavaScript, PHP, PostgreSQl, entre outros.",
        "Participação em feiras de tecnologia e inovação",
        "Desenvolvimento de projetos práticos em programação e automação com Arduíno.",
      ],
    },
  ],
};

export const skillIconsMap: Record<string, string> = {
  HTML: "html",
  CSS: "css",
  Bootstrap: "bootstrap",
  Astro: "astro",
  "React.js": "react",
  Vite: "vite",
  "Framer Motion": "framer",
  "Next.js": "next",
  "Shadcn/ui": "shadcn",
  Vercel: "vercel",
  "Better Auth": "betterauth",
  "Ionic Framework": "ionic",
  Tailwind: "tailwind",
  "Chart.js": "chartjs",
  Javascript: "javascript",
  Typescript: "ts",
  "Node.js": "node",
  "Postman": "postman",
  PHP: "php",
  "C#": "csharp",
  ".NET Framework": "dotnet",
  Prisma: "prisma",
  Supabase: "supabase",
  MySql: "mysql",
  Linux: "linux",
  Git: "git",
  GitHub: "github",
  Docker: "docker",
  Trello: "trello",
  "Metodologias Ágeis": "agile",
  "Lógica de Programação": "logica",
  "Orientação a Objetos": "poo",
};
